### ISSUE TITLE
图标征集令

### ISSUE THREAD

**Issue by william-song-shy** [william-song-shy/ben-ben-spider#4]
现在，本网站需要一个新的图标，欢迎各位贡献  
要求:  
1. **必须**和“爬虫”或(和)“龙王”两个元素相关
2.  不得侵犯他人版权
3. 必须为矢量图  
4. 图标单色

提交方法：发表一个带有`iconwanted`的标签的issue，放上您所创造的图标的文件和缩略图

**Comment by bear-good** [comment]
~~龙在地上爬~~
